# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: annotation


kernel:
    resource: ../src/Kernel.php
    type: annotation

app_association_index:
    path: '/association/'
    controller: 'App\Controller\AssociationController::index'
    methods: ['GET', 'POST']



# config/routes.yaml

# config/services.yaml



